name: Update Amazon Product Prices

on:
  schedule:
    # 每天UTC时间1:00和10:00运行 (对应北京时间9:00和18:00)
    - cron: '0 1,10 * * *'
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run price update
      run: |
        python scripts/update_all_products.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-update Amazon product prices - $(date)"
        git push
